-- JHAYRA Seed: All 50 Products (p001–p050)
-- Run AFTER 003_seed_categories.sql

insert into public.products
  (legacy_id, name, slug, description, category_slug, price, rating, review_count, is_bestseller, is_new_arrival, homepage_visible, display_order, active)
values
  ('p001','Eternal Bloom Canvas','eternal-bloom-canvas','A timeless floral art piece that brings nature''s beauty indoors. Perfect for living rooms and hallways.','personalized',499,4.8,124,true,false,true,1,true),
  ('p002','Golden Sunrise Frame','golden-sunrise-frame','Capture the warmth of a golden sunrise with this premium wall art. Ideal for bedrooms and home offices.','nature',499,4.7,89,true,false,true,2,true),
  ('p003','Sacred Ganesha','sacred-ganesha','A beautifully crafted Ganesha art frame for blessings and positive energy in your home.','religious',499,4.9,201,true,false,true,3,true),
  ('p004','Abstract Horizon','abstract-horizon','Bold abstract art with rich colours and textures. Makes a statement in any modern interior.','modern-art',499,4.6,67,false,true,true,4,true),
  ('p005','Galloping Spirit','galloping-spirit','Vastu-compliant seven running horses wall art symbolising speed, success and prosperity.','running-horses',499,4.8,156,true,false,true,5,true),
  ('p006','Velvet Canvas Print','velvet-canvas-print','A rich, deep-toned canvas print with velvety texture. Perfect for luxury interiors.','canvas',499,4.7,78,false,true,false,6,true),
  ('p007','Crimson Abstract','crimson-abstract','Vibrant crimson and gold abstract art that energises any space.','art-abstract',499,4.5,54,false,false,false,7,true),
  ('p008','Forever Love Frame','forever-love-frame','A romantic art frame celebrating eternal love. Perfect anniversary or wedding gift.','love-romance',499,4.8,112,true,false,true,8,true),
  ('p009','Wedding Bliss','wedding-bliss','Elegant wedding frame capturing the magic of your special day.','wedding',499,4.9,189,true,false,false,9,true),
  ('p010','Family Portrait','family-portrait','A heartwarming family art frame to celebrate your beautiful bonds.','family',499,4.7,93,false,false,false,10,true),
  ('p011','Baby Steps','baby-steps','Adorable baby-themed art frame — a perfect baby shower or newborn gift.','baby-kids',499,4.8,145,true,false,true,11,true),
  ('p012','Paws & Love','paws-and-love','A sweet art frame celebrating your beloved pets. Personalise with your furry friend''s image.','animals-pets',499,4.6,72,false,true,false,12,true),
  ('p013','Birthday Bash Frame','birthday-bash-frame','Bright and cheerful birthday art frame. Makes an unforgettable personalised gift.','occasions',499,4.7,88,false,false,false,13,true),
  ('p014','Golden Hour Photography','golden-hour-photography','Showcase your finest photography with this premium print frame.','photography',499,4.5,45,false,false,false,14,true),
  ('p015','Inspire Daily','inspire-daily','An uplifting motivational quote frame to keep you focused and driven every day.','quotes',499,4.6,61,false,false,false,15,true),
  ('p016','Vastu Peacock','vastu-peacock','Vastu-approved peacock art bringing beauty and good fortune into your home.','home-vastu',499,4.8,134,true,false,true,16,true),
  ('p017','Misty Mountains','misty-mountains','Serene landscape art depicting misty mountain peaks at dawn.','nature',499,4.7,76,false,true,false,17,true),
  ('p018','Lord Shiva Canvas','lord-shiva-canvas','A divine Shiva canvas frame radiating spiritual energy and calm.','religious',499,4.9,167,true,false,false,18,true),
  ('p019','Geometric Dreams','geometric-dreams','Minimalist geometric art with a modern aesthetic. Perfect for contemporary homes.','modern-art',499,4.5,49,false,false,false,19,true),
  ('p020','Wild Mustangs','wild-mustangs','Eight galloping mustangs in motion — an energising wall art for offices and living rooms.','running-horses',499,4.8,121,true,false,false,20,true),
  ('p021','Ocean Breeze Canvas','ocean-breeze-canvas','Breathtaking ocean art capturing the endless blue horizon.','canvas',499,4.6,58,false,true,false,21,true),
  ('p022','Sapphire Abstract','sapphire-abstract','Cool-toned blue and silver abstract art with depth and movement.','art-abstract',499,4.5,42,false,false,false,22,true),
  ('p023','Couple Goals','couple-goals','Sweet couple art frame — personalise with your names and special date.','love-romance',499,4.8,103,true,false,false,23,true),
  ('p024','The Grand Wedding','the-grand-wedding','A majestic wedding frame for your most treasured memories.','wedding',499,4.7,91,false,false,false,24,true),
  ('p025','Family Tree Art','family-tree-art','A symbolic family tree frame to celebrate every branch of your family.','family',499,4.8,118,true,false,false,25,true),
  ('p026','Sweet Baby Moments','sweet-baby-moments','Capture precious first moments with this beautiful baby memory frame.','baby-kids',499,4.9,172,true,false,false,26,true),
  ('p027','Furry Friends Frame','furry-friends-frame','A delightful frame to celebrate your cat, dog or any beloved pet.','animals-pets',499,4.6,65,false,false,false,27,true),
  ('p028','Anniversary Special','anniversary-special','Celebrate years of love with this elegant anniversary art frame.','occasions',499,4.8,109,true,false,false,28,true),
  ('p029','Street Photography Art','street-photography-art','Urban street photography art frame — raw, real and captivating.','photography',499,4.5,38,false,true,false,29,true),
  ('p030','Dream Big Quotes','dream-big-quotes','Powerful motivational quote wall art to inspire greatness every morning.','quotes',499,4.7,82,false,false,false,30,true),
  ('p031','Feng Shui Koi','feng-shui-koi','Lucky koi fish art for wealth, abundance and positive energy flow.','home-vastu',499,4.8,127,true,false,false,31,true),
  ('p032','Cherry Blossom','cherry-blossom','Delicate cherry blossom art capturing the fleeting beauty of spring.','nature',499,4.7,74,false,true,false,32,true),
  ('p033','Om Namah Shivaya','om-namah-shivaya','Sacred Om canvas art spreading divine peace and spiritual vibrations.','religious',499,4.9,193,true,false,false,33,true),
  ('p034','Neon City Art','neon-city-art','Bold neon cityscape modern art for contemporary interiors and gaming setups.','modern-art',499,4.6,56,false,false,false,34,true),
  ('p035','Stallions Power','stallions-power','Majestic stallions wall art symbolising raw power and unstoppable energy.','running-horses',499,4.7,98,true,false,false,35,true),
  ('p036','Textured Canvas','textured-canvas','A premium textured canvas print adding dimension and depth to your walls.','canvas',499,4.5,44,false,false,false,36,true),
  ('p037','Emerald Abstract','emerald-abstract','Lush green abstract art evoking growth, balance and natural harmony.','art-abstract',499,4.6,59,false,false,false,37,true),
  ('p038','Love Letters Frame','love-letters-frame','A romantic personalised frame with your initials and a heartfelt message.','love-romance',499,4.8,107,true,false,false,38,true),
  ('p039','Wedding Vows','wedding-vows','A timeless wedding vows frame to commemorate your promises to each other.','wedding',499,4.8,139,true,false,false,39,true),
  ('p040','Happy Family','happy-family','Vibrant family portrait art celebrating togetherness and joy.','family',499,4.7,85,false,true,false,40,true),
  ('p041','First Birthday','first-birthday','A special first birthday frame — cherish baby''s milestone forever.','baby-kids',499,4.9,161,true,false,false,41,true),
  ('p042','Wildlife Wonder','wildlife-wonder','Majestic wildlife art capturing the splendour of nature''s creatures.','animals-pets',499,4.6,67,false,false,false,42,true),
  ('p043','Festive Diwali Frame','festive-diwali-frame','Bright and festive Diwali art frame — a perfect diwali gift for loved ones.','occasions',499,4.8,148,true,false,false,43,true),
  ('p044','Portrait Masters','portrait-masters','Fine portrait photography art frame showcasing studio-quality elegance.','photography',499,4.5,41,false,false,false,44,true),
  ('p045','Success Mantras','success-mantras','Powerful success mantras wall art to keep you motivated and on track.','quotes',499,4.7,79,false,true,false,45,true),
  ('p046','Lotus Vastu','lotus-vastu','Sacred lotus vastu art for purity, prosperity and positive vibrations.','home-vastu',499,4.8,131,true,false,false,46,true),
  ('p047','Autumn Leaves','autumn-leaves','Warm autumn tones capturing the magic of the season''s change.','nature',499,4.6,62,false,false,false,47,true),
  ('p048','Radha Krishna','radha-krishna','Timeless Radha Krishna divine love art — a spiritual centrepiece for your home.','religious',499,4.9,218,true,false,false,48,true),
  ('p049','Watercolour Bliss','watercolour-bliss','Soft watercolour abstract art with pastel hues and dreamy textures.','art-abstract',499,4.6,53,false,false,false,49,true),
  ('p050','Majestic Sunrise','majestic-sunrise','A breathtaking sunrise canvas capturing the first light of a new day.','personalized',499,4.8,116,true,false,false,50,true)
on conflict (legacy_id) do update set
  name             = excluded.name,
  slug             = excluded.slug,
  description      = excluded.description,
  category_slug    = excluded.category_slug,
  price            = excluded.price,
  rating           = excluded.rating,
  review_count     = excluded.review_count,
  is_bestseller    = excluded.is_bestseller,
  is_new_arrival   = excluded.is_new_arrival,
  display_order    = excluded.display_order;
